/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'system-ui', 'sans-serif'],
      },
      colors: {
        brand: {
          50:  '#fff3ee',
          100: '#ffe4d2',
          200: '#ffc5a0',
          300: '#ff9d65',
          400: '#ff6b2b',
          500: '#FF5A1F',
          600: '#e64a0f',
          700: '#c23a08',
          800: '#9a2f0b',
          900: '#7c280d',
        },
        surface: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#0B0F17',
        },
      },
      spacing: {
        'safe-top':    'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left':   'env(safe-area-inset-left)',
        'safe-right':  'env(safe-area-inset-right)',
        '4.5':  '1.125rem',
        '13':   '3.25rem',
        '15':   '3.75rem',
        '18':   '4.5rem',
        '22':   '5.5rem',
        '26':   '6.5rem',
        '30':   '7.5rem',
      },
      minHeight: {
        'screen-safe': 'calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom))',
        'touch': '44px',
      },
      fontSize: {
        'fluid-xs':  ['clamp(0.75rem, 1.5vw, 0.875rem)',  { lineHeight: '1.5' }],
        'fluid-sm':  ['clamp(0.875rem, 2vw, 1rem)',        { lineHeight: '1.6' }],
        'fluid-md':  ['clamp(1rem, 2.5vw, 1.125rem)',      { lineHeight: '1.6' }],
        'fluid-lg':  ['clamp(1.125rem, 3vw, 1.25rem)',     { lineHeight: '1.5' }],
        'fluid-xl':  ['clamp(1.25rem, 4vw, 1.75rem)',      { lineHeight: '1.4' }],
        'fluid-2xl': ['clamp(1.5rem, 5vw, 2.25rem)',       { lineHeight: '1.3' }],
        'fluid-3xl': ['clamp(1.75rem, 5.5vw, 3rem)',       { lineHeight: '1.2' }],
        'fluid-4xl': ['clamp(2rem, 6vw, 4rem)',            { lineHeight: '1.1' }],
        'fluid-5xl': ['clamp(2.5rem, 7vw, 5rem)',          { lineHeight: '1.05' }],
      },
      borderRadius: {
        'sm':  '0.375rem',
        DEFAULT: '0.5rem',
        'md':  '0.625rem',
        'lg':  '0.75rem',
        'xl':  '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      boxShadow: {
        'professional': '0 1px 3px 0 rgb(0 0 0 / 0.25), 0 1px 2px -1px rgb(0 0 0 / 0.25)',
        'elevated':     '0 4px 12px -1px rgb(0 0 0 / 0.3), 0 2px 6px -2px rgb(0 0 0 / 0.2)',
        'floating':     '0 10px 30px -5px rgb(0 0 0 / 0.4), 0 4px 12px -4px rgb(0 0 0 / 0.2)',
        'brand':        '0 0 0 3px rgba(255, 90, 31, 0.25)',
        'glow-sm':      '0 0 12px rgba(255, 90, 31, 0.3)',
        'glow':         '0 0 24px rgba(255, 90, 31, 0.4)',
      },
      screens: {
        'xs':    '375px',
        'sm':    '640px',
        'md':    '768px',
        'lg':    '1024px',
        'xl':    '1280px',
        '2xl':   '1536px',
        'touch': { raw: '(hover: none) and (pointer: coarse)' },
      },
      animation: {
        'fade-in':     'fadeIn 0.5s ease-out forwards',
        'fade-up':     'fadeUp 0.6s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'scale-in':    'scaleIn 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'slide-down':  'slideDown 0.3s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'pulse-slow':  'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s ease-in-out infinite',
        'spin-slow':   'spin 8s linear infinite',
        'shimmer':     'shimmer 2s linear infinite',
        'scan':        'scan 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(-6px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.94)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        slideDown: {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-500px 0' },
          '100%': { backgroundPosition: '500px 0' },
        },
        scan: {
          '0%':   { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(1200%)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
